### ISSUE TITLE
Error clicking redraw

### ISSUE THREAD

**Issue by barkingfoodog** [Gnomon/MARQUEE_REMOTEFORM_DEMO#1]
Thank you for sharing this! I'm trying to load this example my machine, but I get an error. I've installed the required files into `html/` and the various sub-folders. When I open the library, the remote form opens in my browser. I see a headed list box with three lines of data, and a box containing the word **JANE**. When I click **Redraw**, however, I get this error:
```
Exception occurred when executing client method:
File "http:/﻿/127.0.0.1:57011/jschtml/formscripts/marquee_remoteform_demo/rfmarquee_275_171026085150.js" Line 199

__form.$redraw is not a function. (In '__form.$redraw()', '__form.$redraw' is undefined)
```
Do you know what I might be missing? I'm not very familiar with the JS client, but I would think `$redraw()` is a standard method on the instance.

**Comment by Gnomon** [comment]
please check if user.js is loaded.
$redraw is defined in this file.

**Comment by teneruffian** [comment]
Hi Alex, I had exactly the same problem but fixed it by editing the rfMARQUEE.htm file in the /html directory.  And then refresh the web page.

In the section labelled:
`<!-- Omnis Studio JavaScript client scripts -->`
add the following lines:

`<script type="text/javascript" src="js/libs/react/react.min.js"></script>`
`<script type="text/javascript" src="js/libs/react/react-dom.min.js"></script>`
`<script type="text/javascript" src="js/libs/marquee/marquee.min.js"></script>`
`<script type="text/javascript" src="scripts/user.js"></script>`

HTH.

**Comment by barkingfoodog** [comment]
@teneruffian that fixed it for me as well. Thanks!
